name: "Podcast Generator"
author: "Andrew Jerry V"
decription: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's emial address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: true
    deafult: ${{github.actor}}